### ISSUE TITLE
Create a copy-trading example script

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/smart-margin-integrations#1]
### Context

Kwenta Smart Margin introduces a new feature called Delegation. Delegation allows traders to delegate trading by other parties or services on their behalf. 

Copy-trading requires someone to set up infrastructure to monitor another account (Account A) and then perform actions on behalf of a Account B to copy Account A. To provide an example for integrators that may want to build a copy-trading service, we should build an example script.

### Scope

For this script lets keep it simple and only set up copytrading for one account. So the use case is that someone can clone this script and run it on their own machine so they can set up copytrading for their own account.

### Deliverables 
Build a keeper script that:
- [ ] Allows you to input an account to copy (actively monitors)
- [ ] Performs actions on a delegated account
- [ ] Mirrors the positions of the copied account
- [ ] Written in Typescript
- [ ] Instructions to run it on your own machine with your own account

**Comment by insulineru** [comment]
Implemented here #3
